version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: order-management-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    # هر سه دیتابیس (customerdb, orderdb, paymentdb) در init-db.sql ساخته می‌شوند
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: order-management-rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI -> http://localhost:15672 (guest/guest)

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: order-management-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres-data:
